name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install GraphViz
        run: sudo apt install graphviz libgraphviz-dev
      - name: Install requirements
        run: pip install -r requirements_dev.txt
      - name: Use node.js lts/Gallium
        uses: actions/setup-node@v3
        with:
          node-version: lts/Gallium
      - name: Install dependencies
        run: npm install acorn@8.6.0 -g
      - name: Run unit test
        run: make test
